apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray-daemon
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: xray-daemon
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
      serviceAccountName: xray-daemon
      containers:
        - name: xray-daemon
          image: public.ecr.aws/xray/aws-xray-daemon:latest
          command: ["/usr/bin/xray", "-c", "/aws-xray/config.yaml", "-b", "0.0.0.0:2000", "-o", "-n", "ap-northeast-2"]
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 256m
              memory: 32Mi
          ports:
            - name: xray-ingest
              containerPort: 2000
              protocol: UDP
            - name: xray-tcp
              containerPort: 2000
              protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xray-daemon
  namespace: amazon-cloudwatch
  annotations:
    # Replace with your IAM Role ARN for X-Ray
    eks.amazonaws.com/role-arn: "arn:aws:iam::061039804626:role/NewsugarXRayDaemonRole"
---
apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: amazon-cloudwatch
spec:
  selector:
    app: xray-daemon
  ports:
    - protocol: UDP
      port: 2000
      targetPort: 2000
  type: ClusterIP
