plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.12'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'newsugar'
version = '0.0.1-SNAPSHOT'
description = 'AI-Powered News Summarization Service Backend'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// dotenv 라이브러리입니다. 로컬에서 환경변수 로드할 때 씁니다 운영에선 필요 없어도 의존성 깨지기 싫으면 지우면 안됩니다.
	implementation 'io.github.cdimascio:java-dotenv:5.2.2'
	// JWT 라이브러리들입니다 인증 토큰 만들고 검증하는 놈들입니다. 버전 안 맞으면 에러 나니까 조심하세요.
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// Redis 라이브러리입니다. 캐시나 세션 저장할 때 씁니다
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// 모니터링이랑 분산 추적 툴입니다 서버 뻗거나 느려지면 이걸로 범인 찾습니다.
	implementation 'io.micrometer:micrometer-registry-cloudwatch2'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'com.amazonaws:aws-xray-recorder-sdk-spring:2.18.0'
	implementation 'org.springframework.boot:spring-boot-starter-aop'
}

tasks.named('test') {
	useJUnitPlatform()
}

