apiVersion: v1
kind: Secret
metadata:
  name: newsugar-secrets-prod
  namespace: default
type: Opaque
stringData:
  db-url: "jdbc:mysql://newsugar-prod-aurora-cluster.cluster-c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com:3306/news_db"
  db-username: "admin"
  db-password: "%woH4?VKx1Fn}d2c"
  news-api-key: "23c9561ec76e479fa72778d73ff629f6"
  quiz-ai-api-key: "AIzaSyA2d_2QjmAOVf3MRsvRNDklAfEbrnASgHE"
  jwt-secret: "your_jwt_secret_key_must_be_long_enough_for_security_reasons"
  jwt-refresh-secret: "your_jwt_refresh_secret_key_must_be_long_enough"
