apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newsugar-secrets-prod-es
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: newsugar-secrets-prod
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: newsugar-backend-prod
