apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager-global
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .host }}:3306/news_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
        SPRING_DATASOURCE_USERNAME: "{{ .username }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .password }}"
  data:
  - secretKey: host
    remoteRef:
      key: newsugar/prod/db/auth-59f0a12f
      property: host
  - secretKey: username
    remoteRef:
      key: newsugar/prod/db/auth-59f0a12f
      property: username
  - secretKey: password
    remoteRef:
      key: newsugar/prod/db/auth-59f0a12f
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-app-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager-global
    kind: ClusterSecretStore
  target:
    name: newsugar-secrets-prod
    creationPolicy: Owner
  data:
  - secretKey: NEWS_API_KEY
    remoteRef:
      key: newsugar/prod/app-secrets
      property: NEWS_API_KEY
  - secretKey: QUIZ_AI_API_KEY
    remoteRef:
      key: newsugar/prod/app-secrets
      property: QUIZ_AI_API_KEY
  - secretKey: JWT_SECRET
    remoteRef:
      key: newsugar/prod/app-secrets
      property: JWT_SECRET
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: newsugar/prod/app-secrets
      property: JWT_REFRESH_SECRET
