apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager-global
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: newsugar/prod/db/auth-5e4911f8
      property: host
  - secretKey: DB_USERNAME
    remoteRef:
      key: newsugar/prod/db/auth-5e4911f8
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: newsugar/prod/db/auth-5e4911f8
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-app-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager-global
    kind: ClusterSecretStore
  target:
    name: newsugar-secrets-prod
    creationPolicy: Owner
  data:
  - secretKey: news-api-key
    remoteRef:
      key: newsugar/prod/app-secrets
      property: news-api-key
  - secretKey: quiz-ai-api-key
    remoteRef:
      key: newsugar/prod/app-secrets
      property: quiz-ai-api-key
  - secretKey: jwt-secret
    remoteRef:
      key: newsugar/prod/app-secrets
      property: jwt-secret
  - secretKey: jwt-refresh-secret
    remoteRef:
      key: newsugar/prod/app-secrets
      property: jwt-refresh-secret
