apiVersion: v1
kind: Secret
metadata:
  name: newsugar-secrets-prod
  namespace: default
type: Opaque
stringData:
  # admin
  db-username: "admin"
  # xAGC6oPv2vqwz:DV
  db-password: "xAGC6oPv2vqwz:DV"
  # db-url
  db-url: "jdbc:mysql://newsugar-prod-aurora-cluster.cluster-c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com:3306/news_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
data:
  news-api-key: MjNjOTU2MWVjNzZlNDc5ZmE3Mjc3OGQ3M2ZmNjI5ZjY=
  quiz-ai-api-key: QUl6YVN5QUdpajd2T05tUm54dloyRTdseVN3ZTBCRjc1Ymh0WlNJ
  # 1112279f69471df613ebe55e535ff8cd
  jwt-secret: MTExMjI3OWY2OTQ3MWRmNjEzZWJlNTVlNTM1ZmY4Y2Q=
  jwt-refresh-secret: MWE0YTFlOTY4ZTUzMjE1ZWZmNDdiNDI0ZmEyNDU4OTcxNDAyNTNkOTM0YzRhNTVjNjVlYWMyN2ZiMDQ3OWEwZA==
