apiVersion: v1
kind: Secret
metadata:
  name: newsugar-secrets-prod
  namespace: default
type: Opaque
data:
  # admin
  db-username: YWRtaW4=
  # d]G}N[WHoE2}yl#[
  db-password: PVAyUnJEdiZveyhqI2RCYg==
  # db-url
  db-url: amRiYzpteXNxbDovL25ld3N1Z2FyLXByb2QtYXVyb3JhLWNsdXN0ZXIuY2x1c3Rlci1jM3FtZTZjNmU3ZmouYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206MzMwNi9uZXdzX2RiP3NlcnZlclRpbWV6b25lPUFzaWEvU2VvdWwmY2hhcmFjdGVyRW5jb2Rpbmc9VVRGLTg=
  news-api-key: MjNjOTU2MWVjNzZlNDc5ZmE3Mjc3OGQ3M2ZmNjI5ZjY=
  quiz-ai-api-key: QUl6YVN5QTJkXzJRam1BT1ZmM01Sc3ZSTkRrbEFmRWJybkFTZ0hF
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleV9tdXN0X2JlX2xvbmdfZW5vdWdoX2Zvcl9zZWN1cml0eV9yZWFzb25z
  jwt-refresh-secret: eW91cl9qd3RfcmVmcmVzaF9zZWNyZXRfa2V5X211c3RfYmVfbG9uZ19lbm91Z2g=
