apiVersion: v1
kind: Secret
metadata:
  name: newsugar-secrets-prod
  namespace: default
type: Opaque
data:
  # admin
  db-username: YWRtaW4=
  # VEBXc%tsxo#rx7)i
  db-password: VkVCWGMldHN4byNyeDcpaQ==
  # db-url
  db-url: amRiYzpteXNxbDovL25ld3N1Z2FyLXByb2QtYXVyb3JhLWNsdXN0ZXIuY2x1c3Rlci1jM3FtZTZjNmU3ZmouYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206MzMwNi9uZXdzX2RiP3NlcnZlclRpbWV6b25lPUFzaWEvU2VvdWwmY2hhcmFjdGVyRW5jb2Rpbmc9VVRGLTg=
  news-api-key: MjNjOTU2MWVjNzZlNDc5ZmE3Mjc3OGQ3M2ZmNjI5ZjY=
  quiz-ai-api-key: QUl6YVN5QUdpajd2T05tUm54dloyRTdseVN3ZTBCRjc1Ymh0WlNJ
  # 1112279f69471df613ebe55e535ff8cd
  jwt-secret: MTExMjI3OWY2OTQ3MWRmNjEzZWJlNTVlNTM1ZmY4Y2Q=
  # 1a4a1e968e53215eff47b424fa245897140253d934c4a55c65eac27fb0479a0d
  jwt-refresh-secret: MWE0YTFlOTY4ZTUzMjE1ZWZmNDdiNDI0ZmEyNDU4OTcxNDAyNTNkOTM0YzRhNTVjNjVlYWMyN2ZiMDQ3OWEwZA==
